-- Persistent booking event feed generated by the Beds24 booking sync.

CREATE TABLE booking_events (
    booking_event_id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type TEXT NOT NULL CHECK (event_type IN ('new', 'updated', 'cancelled')),
    booking_id INTEGER NOT NULL,
    beds24_booking_id INTEGER NOT NULL,
    accommodation TEXT NOT NULL,
    source TEXT,
    event_signature TEXT NOT NULL UNIQUE,
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL,

    FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX idx_booking_events_recent
    ON booking_events(occurred_at DESC, booking_event_id DESC);

CREATE INDEX idx_booking_events_booking
    ON booking_events(beds24_booking_id, occurred_at DESC);
